### ISSUE TITLE
Doesn’t work with karma 1.x

### ISSUE THREAD

**Issue by arty-name** [prodatakey/karma-dirty-chai#8]
The inclusion of karma-dirty-chai adapter breaks karma in mysterious ways. #7 fixes that issue.

**Comment by andrej-urvantsev** [comment]
Seems like it's been fixed in karma 1.1.2:
https://github.com/karma-runner/karma/commit/4d1bf3e
https://github.com/karma-runner/karma/issues/2194

**Comment by arty-name** [comment]
True! Let’s consider that a karma issue, not this module’s.
